task :compile do
  sh "g++ -o komplex++ Komplex.cpp"
  sh "gcc -o komplex Komplex.c"
  sh "javac *.java"
end

task :run => :compile do
  sh "./komplex"
  sh "js komplex.js"
  sh "ruby komplex.rb"
  sh "java KomplexMain"
  sh "./komplex++"
end

task :ps do
  sh "a2ps -o komplex.ps README.txt typescript *.c *.js *.rb *.java *.cpp"
end