task :compile do
  sh "g++ -o komplex++ Komplex.cpp"
  sh "gcc -o komplex Komplex.c"
  sh "javac *.java"
end

task :run => :compile do
  sh "./komplex++"
  sh "./komplex"
  sh "ruby komplex.rb"
  sh "java KomplexMain"
end